apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":true,"kind":"ServiceAccount","metadata":{"annotations":{"helm.sh/hook":"pre-install,pre-upgrade","helm.sh/hook-delete-policy":"before-hook-creation,hook-succeeded"},"labels":{"app.kubernetes.io/component":"contour-certgen","app.kubernetes.io/instance":"contour","app.kubernetes.io/managed-by":"pulumi","app.kubernetes.io/name":"contour","helm.sh/chart":"contour-11.0.0"},"name":"contour-contour-certgen","namespace":"projectcontour"}}
  creationTimestamp: "2023-02-27T05:34:23Z"
  labels:
    app.kubernetes.io/component: contour-certgen
    app.kubernetes.io/instance: contour
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: contour
    helm.sh/chart: contour-11.0.0
  name: contour-contour-certgen
  namespace: projectcontour
  resourceVersion: "18212"
  uid: d4b9a66e-2e16-4cd8-bd6a-b54f202529b8
