apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-eventhandler
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: node-exporter
  namespace: default
spec:
  config:
    autoscrape:
      enable: true
      metrics_instance: default/grafana-agent
    procfs_path: host/proc
    rootfs_path: /host/root
    sysfs_path: /host/sys
  name: node_exporter
  type:
    allNodes: true
    unique: true
  volumeMounts:
    - mountPath: /host/root
      name: rootfs
    - mountPath: /host/sys
      name: sysfs
    - mountPath: /host/proc
      name: procfs
  volumes:
    - hostPath:
        path: /
      name: rootfs
    - hostPath:
        path: /sys
      name: sysfs
    - hostPath:
        path: /proc
      name: procfs

---
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent
  name: agent-eventhandler
  namespace: default
spec:
  config:
    cache_path: /etc/eventhandler/eventhandler.cache
    logs_instance: default/grafana-agent-logs
  name: eventhandler
  type:
    unique: true
  volumeMounts:
    - mountPath: /etc/eventhandler
      name: agent-eventhandler
  volumes:
    - name: agent-eventhandler
      persistentVolumeClaim:
        claimName: agent-eventhandler
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: cadvisor-monitor
  namespace: default
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      interval: 60s
      metricRelabelings:
        - action: keep
          regex: storage_operation_duration_seconds_count|kubelet_volume_stats_capacity_bytes|kube_node_info|namespace_cpu:kube_pod_container_resource_limits:sum|namespace_memory:kube_pod_container_resource_limits:sum|kube_statefulset_status_observed_generation|container_network_receive_bytes_total|rest_client_requests_total|kube_horizontalpodautoscaler_status_desired_replicas|kube_statefulset_status_replicas|container_fs_reads_bytes_total|namespace_workload_pod:kube_pod_owner:relabel|kubelet_running_pods|go_goroutines|kubelet_certificate_manager_server_ttl_seconds|namespace_memory:kube_pod_container_resource_requests:sum|container_memory_working_set_bytes|kube_node_spec_taint|kube_pod_owner|container_memory_cache|kubelet_pod_worker_duration_seconds_bucket|kubelet_node_config_error|kubelet_runtime_operations_errors_total|kube_pod_container_status_waiting_reason|kube_deployment_status_replicas_available|kube_statefulset_status_current_revision|node_namespace_pod_container:container_memory_rss|container_cpu_usage_seconds_total|kube_job_status_start_time|kube_statefulset_status_update_revision|process_resident_memory_bytes|container_network_receive_packets_total|kubelet_pod_start_duration_seconds_count|volume_manager_total_volumes|node_namespace_pod_container:container_memory_cache|kube_node_status_allocatable|kube_horizontalpodautoscaler_spec_max_replicas|process_cpu_seconds_total|kubelet_running_pod_count|kube_pod_container_resource_requests|kubelet_running_containers|kube_deployment_spec_replicas|kubelet_server_expiration_renew_errors|namespace_workload_pod|container_memory_swap|kubelet_cgroup_manager_duration_seconds_count|kube_daemonset_status_number_available|container_network_transmit_bytes_total|kubelet_pleg_relist_interval_seconds_bucket|container_cpu_cfs_periods_total|kube_daemonset_status_updated_number_scheduled|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_job_failed|container_network_transmit_packets_total|kubelet_pod_worker_duration_seconds_count|kubelet_volume_stats_available_bytes|kube_horizontalpodautoscaler_spec_min_replicas|container_fs_reads_total|kube_deployment_status_observed_generation|kube_statefulset_status_replicas_updated|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_running_container_count|kube_pod_info|kube_daemonset_status_number_misscheduled|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|container_cpu_cfs_throttled_periods_total|kube_daemonset_status_current_number_scheduled|node_namespace_pod_container:container_memory_swap|kube_job_status_active|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|kubelet_pod_start_duration_seconds_bucket|container_network_transmit_packets_dropped_total|kubelet_node_name|kube_daemonset_status_desired_number_scheduled|machine_memory_bytes|kubelet_cgroup_manager_duration_seconds_bucket|kube_pod_container_resource_limits|kubelet_runtime_operations_total|kube_deployment_status_replicas_updated|kubernetes_build_info|container_fs_writes_bytes_total|container_network_receive_packets_dropped_total|kube_pod_status_phase|kube_statefulset_replicas|kube_replicaset_owner|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|container_memory_rss|kube_resourcequota|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kubelet_volume_stats_inodes_used|node_namespace_pod_container:container_memory_working_set_bytes|kube_deployment_metadata_generation|kube_horizontalpodautoscaler_status_current_replicas|kube_node_status_capacity|kubelet_pleg_relist_duration_seconds_count|container_fs_writes_total|kubelet_pleg_relist_duration_seconds_bucket|kubelet_volume_stats_inodes|kube_statefulset_status_replicas_ready|kube_node_status_condition|kubelet_certificate_manager_client_ttl_seconds|namespace_cpu:kube_pod_container_resource_requests:sum|storage_operation_errors_total|kube_statefulset_metadata_generation|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|kube_namespace_status_phase|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node.*|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum|node_cpu.*|node_memory.*|node_filesystem.*
          sourceLabels:
            - __name__
      path: /metrics/cadvisor
      port: https-metrics
      relabelings:
        - sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
        - action: replace
          replacement: integrations/kubernetes/cadvisor
          targetLabel: job
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: ksm-monitor
  namespace: default
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      metricRelabelings:
        - action: keep
          regex: storage_operation_duration_seconds_count|kubelet_volume_stats_capacity_bytes|kube_node_info|namespace_cpu:kube_pod_container_resource_limits:sum|namespace_memory:kube_pod_container_resource_limits:sum|kube_statefulset_status_observed_generation|container_network_receive_bytes_total|rest_client_requests_total|kube_horizontalpodautoscaler_status_desired_replicas|kube_statefulset_status_replicas|container_fs_reads_bytes_total|namespace_workload_pod:kube_pod_owner:relabel|kubelet_running_pods|go_goroutines|kubelet_certificate_manager_server_ttl_seconds|namespace_memory:kube_pod_container_resource_requests:sum|container_memory_working_set_bytes|kube_node_spec_taint|kube_pod_owner|container_memory_cache|kubelet_pod_worker_duration_seconds_bucket|kubelet_node_config_error|kubelet_runtime_operations_errors_total|kube_pod_container_status_waiting_reason|kube_deployment_status_replicas_available|kube_statefulset_status_current_revision|node_namespace_pod_container:container_memory_rss|container_cpu_usage_seconds_total|kube_job_status_start_time|kube_statefulset_status_update_revision|process_resident_memory_bytes|container_network_receive_packets_total|kubelet_pod_start_duration_seconds_count|volume_manager_total_volumes|node_namespace_pod_container:container_memory_cache|kube_node_status_allocatable|kube_horizontalpodautoscaler_spec_max_replicas|process_cpu_seconds_total|kubelet_running_pod_count|kube_pod_container_resource_requests|kubelet_running_containers|kube_deployment_spec_replicas|kubelet_server_expiration_renew_errors|namespace_workload_pod|container_memory_swap|kubelet_cgroup_manager_duration_seconds_count|kube_daemonset_status_number_available|container_network_transmit_bytes_total|kubelet_pleg_relist_interval_seconds_bucket|container_cpu_cfs_periods_total|kube_daemonset_status_updated_number_scheduled|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_job_failed|container_network_transmit_packets_total|kubelet_pod_worker_duration_seconds_count|kubelet_volume_stats_available_bytes|kube_horizontalpodautoscaler_spec_min_replicas|container_fs_reads_total|kube_deployment_status_observed_generation|kube_statefulset_status_replicas_updated|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_running_container_count|kube_pod_info|kube_daemonset_status_number_misscheduled|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|container_cpu_cfs_throttled_periods_total|kube_daemonset_status_current_number_scheduled|node_namespace_pod_container:container_memory_swap|kube_job_status_active|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|kubelet_pod_start_duration_seconds_bucket|container_network_transmit_packets_dropped_total|kubelet_node_name|kube_daemonset_status_desired_number_scheduled|machine_memory_bytes|kubelet_cgroup_manager_duration_seconds_bucket|kube_pod_container_resource_limits|kubelet_runtime_operations_total|kube_deployment_status_replicas_updated|kubernetes_build_info|container_fs_writes_bytes_total|container_network_receive_packets_dropped_total|kube_pod_status_phase|kube_statefulset_replicas|kube_replicaset_owner|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|container_memory_rss|kube_resourcequota|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kubelet_volume_stats_inodes_used|node_namespace_pod_container:container_memory_working_set_bytes|kube_deployment_metadata_generation|kube_horizontalpodautoscaler_status_current_replicas|kube_node_status_capacity|kubelet_pleg_relist_duration_seconds_count|container_fs_writes_total|kubelet_pleg_relist_duration_seconds_bucket|kubelet_volume_stats_inodes|kube_statefulset_status_replicas_ready|kube_node_status_condition|kubelet_certificate_manager_client_ttl_seconds|namespace_cpu:kube_pod_container_resource_requests:sum|storage_operation_errors_total|kube_statefulset_metadata_generation|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|kube_namespace_status_phase|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node.*|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum|node_cpu.*|node_memory.*|node_filesystem.*
          sourceLabels:
            - __name__
      path: /metrics
      port: http-metrics
      relabelings:
        - action: replace
          replacement: integrations/kubernetes/kube-state-metrics
          targetLabel: job
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    instance: primary
  name: kubelet-monitor
  namespace: default
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      interval: 60s
      metricRelabelings:
        - action: keep
          regex: storage_operation_duration_seconds_count|kubelet_volume_stats_capacity_bytes|kube_node_info|namespace_cpu:kube_pod_container_resource_limits:sum|namespace_memory:kube_pod_container_resource_limits:sum|kube_statefulset_status_observed_generation|container_network_receive_bytes_total|rest_client_requests_total|kube_horizontalpodautoscaler_status_desired_replicas|kube_statefulset_status_replicas|container_fs_reads_bytes_total|namespace_workload_pod:kube_pod_owner:relabel|kubelet_running_pods|go_goroutines|kubelet_certificate_manager_server_ttl_seconds|namespace_memory:kube_pod_container_resource_requests:sum|container_memory_working_set_bytes|kube_node_spec_taint|kube_pod_owner|container_memory_cache|kubelet_pod_worker_duration_seconds_bucket|kubelet_node_config_error|kubelet_runtime_operations_errors_total|kube_pod_container_status_waiting_reason|kube_deployment_status_replicas_available|kube_statefulset_status_current_revision|node_namespace_pod_container:container_memory_rss|container_cpu_usage_seconds_total|kube_job_status_start_time|kube_statefulset_status_update_revision|process_resident_memory_bytes|container_network_receive_packets_total|kubelet_pod_start_duration_seconds_count|volume_manager_total_volumes|node_namespace_pod_container:container_memory_cache|kube_node_status_allocatable|kube_horizontalpodautoscaler_spec_max_replicas|process_cpu_seconds_total|kubelet_running_pod_count|kube_pod_container_resource_requests|kubelet_running_containers|kube_deployment_spec_replicas|kubelet_server_expiration_renew_errors|namespace_workload_pod|container_memory_swap|kubelet_cgroup_manager_duration_seconds_count|kube_daemonset_status_number_available|container_network_transmit_bytes_total|kubelet_pleg_relist_interval_seconds_bucket|container_cpu_cfs_periods_total|kube_daemonset_status_updated_number_scheduled|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_job_failed|container_network_transmit_packets_total|kubelet_pod_worker_duration_seconds_count|kubelet_volume_stats_available_bytes|kube_horizontalpodautoscaler_spec_min_replicas|container_fs_reads_total|kube_deployment_status_observed_generation|kube_statefulset_status_replicas_updated|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_running_container_count|kube_pod_info|kube_daemonset_status_number_misscheduled|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|container_cpu_cfs_throttled_periods_total|kube_daemonset_status_current_number_scheduled|node_namespace_pod_container:container_memory_swap|kube_job_status_active|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|kubelet_pod_start_duration_seconds_bucket|container_network_transmit_packets_dropped_total|kubelet_node_name|kube_daemonset_status_desired_number_scheduled|machine_memory_bytes|kubelet_cgroup_manager_duration_seconds_bucket|kube_pod_container_resource_limits|kubelet_runtime_operations_total|kube_deployment_status_replicas_updated|kubernetes_build_info|container_fs_writes_bytes_total|container_network_receive_packets_dropped_total|kube_pod_status_phase|kube_statefulset_replicas|kube_replicaset_owner|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|container_memory_rss|kube_resourcequota|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kubelet_volume_stats_inodes_used|node_namespace_pod_container:container_memory_working_set_bytes|kube_deployment_metadata_generation|kube_horizontalpodautoscaler_status_current_replicas|kube_node_status_capacity|kubelet_pleg_relist_duration_seconds_count|container_fs_writes_total|kubelet_pleg_relist_duration_seconds_bucket|kubelet_volume_stats_inodes|kube_statefulset_status_replicas_ready|kube_node_status_condition|kubelet_certificate_manager_client_ttl_seconds|namespace_cpu:kube_pod_container_resource_requests:sum|storage_operation_errors_total|kube_statefulset_metadata_generation|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|kube_namespace_status_phase|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node.*|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum|node_cpu.*|node_memory.*|node_filesystem.*
          sourceLabels:
            - __name__
      path: /metrics
      port: https-metrics
      relabelings:
        - sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
        - action: replace
          replacement: integrations/kubernetes/kubelet
          targetLabel: job
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
---
