kafka_values = {
    "global": {
        "imageRegistry": "",
        "imagePullSecrets": [],
        "storageClass": ""
    },
    "kubeVersion": "",
    "nameOverride": "",
    "fullnameOverride": "",
    "clusterDomain": "cluster.local",
    "commonLabels": {},
    "commonAnnotations": {},
    "extraDeploy": [],
    "diagnosticMode": {
        "enabled": False,
        "command": [
            "sleep"
        ],
        "args": [
            "infinity"
        ]
    },
    "image": {
        "registry": "docker.io",
        "repository": "bitnami/kafka",
        "tag": "3.3.2-debian-11-r0",
        "digest": "",
        "pullPolicy": "IfNotPresent",
        "pullSecrets": [],
        "debug": False
    },
    "config": "",
    "existingConfigmap": "",
    "log4j": "",
    "existingLog4jConfigMap": "",
    "heapOpts": "-Xmx1024m -Xms1024m",
    "deleteTopicEnable": False,
    "autoCreateTopicsEnable": True,
    "logFlushIntervalMessages": "_10000",
    "logFlushIntervalMs": 1000,
    "logRetentionBytes": "_1073741824",
    "logRetentionCheckIntervalMs": 300000,
    "logRetentionHours": 168,
    "logSegmentBytes": "_1073741824",
    "logsDirs": "/bitnami/kafka/data",
    "maxMessageBytes": "_1000012",
    "defaultReplicationFactor": 2,
    "offsetsTopicReplicationFactor": 1,
    "transactionStateLogReplicationFactor": 1,
    "transactionStateLogMinIsr": 1,
    "numIoThreads": 8,
    "numNetworkThreads": 3,
    "numPartitions": 1,
    "numRecoveryThreadsPerDataDir": 1,
    "socketReceiveBufferBytes": 102400,
    "socketRequestMaxBytes": "_104857600",
    "socketSendBufferBytes": 102400,
    "zookeeperConnectionTimeoutMs": 6000,
    "zookeeperChrootPath": "",
    "authorizerClassName": "",
    "allowEveryoneIfNoAclFound": True,
    "superUsers": "User:admin",
    "auth": {
        "clientProtocol": "plaintext",
        "externalClientProtocol": "",
        "interBrokerProtocol": "plaintext",
        "sasl": {
            "mechanisms": "plain,scram-sha-256,scram-sha-512",
            "interBrokerMechanism": "plain",
            "jaas": {
                "clientUsers": [
                    "user"
                ],
                "clientPasswords": [],
                "interBrokerUser": "admin",
                "interBrokerPassword": "",
                "zookeeperUser": "",
                "zookeeperPassword": "",
                "existingSecret": ""
            }
        },
        "tls": {
            "type": "jks",
            "pemChainIncluded": False,
            "existingSecrets": [],
            "autoGenerated": False,
            "password": "",
            "existingSecret": "",
            "jksTruststoreSecret": "",
            "jksKeystoreSAN": "",
            "jksTruststore": "",
            "endpointIdentificationAlgorithm": "https"
        },
        "zookeeper": {
            "tls": {
                "enabled": False,
                "type": "jks",
                "verifyHostname": True,
                "existingSecret": "",
                "existingSecretKeystoreKey": "zookeeper.keystore.jks",
                "existingSecretTruststoreKey": "zookeeper.truststore.jks",
                "passwordsSecret": "",
                "passwordsSecretKeystoreKey": "keystore-password",
                "passwordsSecretTruststoreKey": "truststore-password"
            }
        }
    },
    "listeners": [],
    "advertisedListeners": [],
    "listenerSecurityProtocolMap": "",
    "allowPlaintextListener": True,
    "interBrokerListenerName": "INTERNAL",
    "command": [
        "/scripts/setup.sh"
    ],
    "args": [],
    "extraEnvVars": [],
    "extraEnvVarsCM": "",
    "extraEnvVarsSecret": "",
    "replicaCount": 2,
    "minBrokerId": 0,
    "brokerRackAssignment": "",
    "containerPorts": {
        "client": 9092,
        "internal": 9093,
        "external": 9094
    },
    "livenessProbe": {
        "enabled": True,
        "initialDelaySeconds": 10,
        "timeoutSeconds": 5,
        "failureThreshold": 3,
        "periodSeconds": 10,
        "successThreshold": 1
    },
    "readinessProbe": {
        "enabled": True,
        "initialDelaySeconds": 5,
        "failureThreshold": 6,
        "timeoutSeconds": 5,
        "periodSeconds": 10,
        "successThreshold": 1
    },
    "startupProbe": {
        "enabled": False,
        "initialDelaySeconds": 30,
        "periodSeconds": 10,
        "timeoutSeconds": 1,
        "failureThreshold": 15,
        "successThreshold": 1
    },
    "customLivenessProbe": {},
    "customReadinessProbe": {},
    "customStartupProbe": {},
    "lifecycleHooks": {},
    "resources": {
        "limits": {},
        "requests": {}
    },
    "podSecurityContext": {
        "enabled": True,
        "fsGroup": 1001
    },
    "containerSecurityContext": {
        "enabled": True,
        "runAsUser": 1001,
        "runAsNonRoot": True,
        "allowPrivilegeEscalation": False
    },
    "hostAliases": [],
    "hostNetwork": False,
    "hostIPC": False,
    "podLabels": {},
    "podAnnotations": {},
    "podAffinityPreset": "",
    "podAntiAffinityPreset": "soft",
    "nodeAffinityPreset": {
        "type": "",
        "key": "",
        "values": []
    },
    "affinity": {},
    "nodeSelector": {},
    "tolerations": [],
    "topologySpreadConstraints": [],
    "terminationGracePeriodSeconds": "",
    "podManagementPolicy": "Parallel",
    "priorityClassName": "",
    "schedulerName": "",
    "updateStrategy": {
        "type": "RollingUpdate",
        "rollingUpdate": {}
    },
    "extraVolumes": [],
    "extraVolumeMounts": [],
    "sidecars": [],
    "initContainers": [],
    "pdb": {
        "create": False,
        "minAvailable": "",
        "maxUnavailable": 1
    },
    "service": {
        "type": "ClusterIP",
        "ports": {
            "client": 9092,
            "internal": 9093,
            "external": 9094
        },
        "nodePorts": {
            "client": "",
            "external": ""
        },
        "sessionAffinity": "None",
        "sessionAffinityConfig": {},
        "clusterIP": "",
        "loadBalancerIP": "",
        "loadBalancerSourceRanges": [],
        "externalTrafficPolicy": "Cluster",
        "annotations": {},
        "headless": {
            "publishNotReadyAddresses": False,
            "annotations": {},
            "labels": {}
        },
        "extraPorts": []
    },
    "externalAccess": {
        "enabled": True,
        "autoDiscovery": {
            "enabled": True,
            "image": {
                "registry": "docker.io",
                "repository": "bitnami/kubectl",
                "tag": "1.25.6-debian-11-r1",
                "digest": "",
                "pullPolicy": "IfNotPresent",
                "pullSecrets": []
            },
            "resources": {
                "limits": {},
                "requests": {}
            }
        },
        "service": {
            "type": "ClusterIP",
            "ports": {
                "external": 9094
            },
            "loadBalancerIPs": [],
            "loadBalancerNames": [],
            "loadBalancerAnnotations": [],
            "loadBalancerSourceRanges": [],
            "nodePorts": [],
            "useHostIPs": False,
            "usePodIPs": False,
            "domain": "cluster.local",
            "publishNotReadyAddresses": False,
            "labels": {},
            "annotations": {},
            "extraPorts": []
        }
    },
    "networkPolicy": {
        "enabled": False,
        "allowExternal": True,
        "explicitNamespacesSelector": {},
        "externalAccess": {
            "from": []
        },
        "egressRules": {
            "customRules": []
        }
    },
    "persistence": {
        "enabled": True,
        "existingClaim": "",
        "storageClass": "",
        "accessModes": [
            "ReadWriteOnce"
        ],
        "size": "8Gi",
        "annotations": {},
        "labels": {},
        "selector": {},
        "mountPath": "/bitnami/kafka"
    },
    "logPersistence": {
        "enabled": False,
        "existingClaim": "",
        "storageClass": "",
        "accessModes": [
            "ReadWriteOnce"
        ],
        "size": "8Gi",
        "annotations": {},
        "selector": {},
        "mountPath": "/opt/bitnami/kafka/logs"
    },
    "volumePermissions": {
        "enabled": False,
        "image": {
            "registry": "docker.io",
            "repository": "bitnami/bitnami-shell",
            "tag": "11-debian-11-r75",
            "digest": "",
            "pullPolicy": "IfNotPresent",
            "pullSecrets": []
        },
        "resources": {
            "limits": {},
            "requests": {}
        },
        "containerSecurityContext": {
            "runAsUser": 0
        }
    },
    "serviceAccount": {
        "create": True,
        "name": "",
        "automountServiceAccountToken": True,
        "annotations": {}
    },
    "rbac": {
        "create": True
    },
    "metrics": {
        "kafka": {
            "enabled": False,
            "image": {
                "registry": "docker.io",
                "repository": "bitnami/kafka-exporter",
                "tag": "1.6.0-debian-11-r52",
                "digest": "",
                "pullPolicy": "IfNotPresent",
                "pullSecrets": []
            },
            "certificatesSecret": "",
            "tlsCert": "cert-file",
            "tlsKey": "key-file",
            "tlsCaSecret": "",
            "tlsCaCert": "ca-file",
            "extraFlags": {},
            "command": [],
            "args": [],
            "containerPorts": {
                "metrics": 9308
            },
            "resources": {
                "limits": {},
                "requests": {}
            },
            "podSecurityContext": {
                "enabled": True,
                "fsGroup": 1001
            },
            "containerSecurityContext": {
                "enabled": True,
                "runAsUser": 1001,
                "runAsNonRoot": True
            },
            "hostAliases": [],
            "podLabels": {},
            "podAnnotations": {},
            "podAffinityPreset": "",
            "podAntiAffinityPreset": "soft",
            "nodeAffinityPreset": {
                "type": "",
                "key": "",
                "values": []
            },
            "affinity": {},
            "nodeSelector": {},
            "tolerations": [],
            "schedulerName": "",
            "priorityClassName": "",
            "topologySpreadConstraints": [],
            "extraVolumes": [],
            "extraVolumeMounts": [],
            "sidecars": [],
            "initContainers": [],
            "service": {
                "ports": {
                    "metrics": 9308
                },
                "clusterIP": "",
                "sessionAffinity": "None",
            },
            "serviceAccount": {
                "create": True,
                "name": "",
                "automountServiceAccountToken": True
            }
        },
        "jmx": {
            "enabled": True,
            "image": {
                "registry": "docker.io",
                "repository": "bitnami/jmx-exporter",
                "tag": "0.17.2-debian-11-r41",
                "digest": "",
                "pullPolicy": "IfNotPresent",
                "pullSecrets": []
            },
            "containerSecurityContext": {
                "enabled": True,
                "runAsUser": 1001,
                "runAsNonRoot": True
            },
            "containerPorts": {
                "metrics": 5556
            },
            "resources": {
                "limits": {},
                "requests": {}
            },
            "service": {
                "ports": {
                    "metrics": 5556
                },
                "clusterIP": "",
                "sessionAffinity": "None",
                "annotations": {
                    "prometheus.io/scrape": "True",
                    "prometheus.io/port": "{{ .Values.metrics.jmx.service.ports.metrics }}",
                    "prometheus.io/path": "/"
                }
            },
            "whitelistObjectNames": [
                "kafka.controller:*",
                "kafka.server:*",
                "java.lang:*",
                "kafka.network:*",
                "kafka.log:*"
            ],
            "config": "jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi\nlowercaseOutputName: True\nlowercaseOutputLabelNames: True\nssl: False\n{{- if .Values.metrics.jmx.whitelistObjectNames }}\nwhitelistObjectNames: [\"{{ join \"\\\",\\\"\" .Values.metrics.jmx.whitelistObjectNames }}\"]\n{{- end }}",
            "existingConfigmap": "",
            "extraRules": ""
        },
        "serviceMonitor": {
            "enabled": False,
            "namespace": "",
            "interval": "",
            "scrapeTimeout": "",
            "labels": {},
            "selector": {},
            "relabelings": [],
            "metricRelabelings": [],
            "honorLabels": False,
            "jobLabel": ""
        },
        "prometheusRule": {
            "enabled": False,
            "namespace": "",
            "labels": {},
            "groups": []
        }
    },
    "provisioning": {
        "enabled": False,
        "numPartitions": 1,
        "replicationFactor": 1,
        "topics": [],
        "nodeSelector": {},
        "tolerations": [],
        "extraProvisioningCommands": [],
        "parallel": 1,
        "preScript": "",
        "postScript": "",
        "auth": {
            "tls": {
                "type": "jks",
                "certificatesSecret": "",
                "cert": "tls.crt",
                "key": "tls.key",
                "caCert": "ca.crt",
                "keystore": "keystore.jks",
                "truststore": "truststore.jks",
                "passwordsSecret": "",
                "keyPasswordSecretKey": "key-password",
                "keystorePasswordSecretKey": "keystore-password",
                "truststorePasswordSecretKey": "truststore-password",
                "keyPassword": "",
                "keystorePassword": "",
                "truststorePassword": ""
            }
        },
        "command": [],
        "args": [],
        "extraEnvVars": [],
        "extraEnvVarsCM": "",
        "extraEnvVarsSecret": "",
        "podAnnotations": {},
        "podLabels": {},
        "serviceAccount": {
            "create": False,
            "name": "",
            "automountServiceAccountToken": True
        },
        "resources": {
            "limits": {},
            "requests": {}
        },
        "podSecurityContext": {
            "enabled": True,
            "fsGroup": 1001
        },
        "containerSecurityContext": {
            "enabled": True,
            "runAsUser": 1001,
            "runAsNonRoot": True
        },
        "schedulerName": "",
        "extraVolumes": [],
        "extraVolumeMounts": [],
        "sidecars": [],
        "initContainers": [],
        "waitForKafka": True
    },
    "zookeeper": {
        "enabled": True,
        "replicaCount": 1,
        "auth": {
            "client": {
                "enabled": False,
                "clientUser": "",
                "clientPassword": "",
                "serverUsers": "",
                "serverPasswords": ""
            }
        },
        "persistence": {
            "enabled": True,
            "storageClass": "",
            "accessModes": [
                "ReadWriteOnce"
            ],
            "size": "8Gi"
        }
    },
    "externalZookeeper": {
        "servers": []
    }
}
